import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { sendSettlementReport } from '@/lib/email/service';
import { sanitizeCSVValue } from '@/lib/csv-sanitizer';
import Decimal from 'decimal.js';

interface Profile {
  role: string;
  full_name: string;
}

interface Event {
  event_id: string;
  title: string;
  date_time: string;
  status: string;
  ticket_price: number;
  convene_commission_percentage: number;
  settlement_status: string | null;
}

interface Booking {
  booking_id: string;
  tickets_count: number;
  total_amount: number;
  payment_status: string;
}

interface Settlement {
  settlement_id: string;
  transaction_reference: string | null;
  transfer_date: string | null;
  payment_method: string | null;
  notes: string | null;
  gross_revenue: number;
  razorpay_fees: number;
  convene_commission: number;
  net_payout: number;
}

interface SettlementDetails {
  event_title: string;
  event_date: string;
  gross_revenue: number;
  razorpay_fees: number;
  convene_commission: number;
  net_payout: number;
  tickets_sold: number;
  settlement_status: string;
  transaction_reference?: string;
  transfer_date?: string;
  payment_method?: string;
  notes?: string;
}

/**
 * Generate CSV content for settlement report
 */
function generateSettlementCSV(details: SettlementDetails, event: Event, bookings: Booking[]): string {
  const lines: string[] = [];

  // Professional header with metadata
  lines.push('CONVENEHUB SETTLEMENT REPORT');
  lines.push(`Generated: ${new Date().toLocaleString('en-IN')}`);
  lines.push(`Report Date: ${new Date().toLocaleDateString('en-IN')}`);
  lines.push('');
  lines.push('─'.repeat(80));
  lines.push('');

  // Event Information Section
  lines.push('EVENT DETAILS');
  lines.push('─'.repeat(80));
  lines.push(`Event Name,"${sanitizeCSVValue(details.event_title)}"`);
  lines.push(`Event Date,${new Date(details.event_date).toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push(`Total Tickets Sold,${details.tickets_sold}`);
  lines.push('');

  // Financial Summary Section
  lines.push('FINANCIAL BREAKDOWN');
  lines.push('─'.repeat(80));
  lines.push('Category,Amount (INR),Notes');
  lines.push(`Gross Revenue,"₹${details.gross_revenue.toFixed(2)}","Total revenue from all confirmed tickets"`);
  lines.push(`Razorpay Gateway Fees,"₹${details.razorpay_fees.toFixed(2)}","2% payment gateway charge"`);
  lines.push(`CONVENEHUB Commission,"₹${details.convene_commission.toFixed(2)}","10% platform commission"`);
  lines.push(`Net Payout,"₹${details.net_payout.toFixed(2)}","Final amount payable to production team"`);
  lines.push('');

  // Booking Details Section
  if (bookings && bookings.length > 0) {
    lines.push('BOOKING DETAILS');
    lines.push('─'.repeat(80));
    lines.push('Booking ID,Number of Tickets,Amount (INR),Payment Status,Notes');
    
    let totalBookingAmount = 0;
    bookings.forEach((booking, index) => {
      const bookingAmount = booking.total_amount || 0;
      totalBookingAmount += bookingAmount;
      lines.push(
        `${sanitizeCSVValue(booking.booking_id)},${booking.tickets_count},"₹${bookingAmount.toFixed(2)}",${sanitizeCSVValue(booking.payment_status)},"Booking #${index + 1}"`
      );
    });
    
    lines.push('');
    lines.push(`Total,${bookings.length} bookings,"₹${totalBookingAmount.toFixed(2)}","","Verified total"`);
    lines.push('');
  }

  // Settlement Status Section
  lines.push('SETTLEMENT STATUS');
  lines.push('─'.repeat(80));
  lines.push(`Status,${details.settlement_status.toUpperCase()}`);
  
  if (details.settlement_status === 'settled' && details.transaction_reference) {
    lines.push(`Transaction Reference,${sanitizeCSVValue(details.transaction_reference)}`);
    if (details.transfer_date) {
      lines.push(`Transfer Date,${new Date(details.transfer_date).toLocaleDateString('en-IN')}`);
    }
    if (details.payment_method) {
      lines.push(`Payment Method,${sanitizeCSVValue(details.payment_method.replace(/_/g, ' ').toUpperCase())}`);
    }
  }
  
  if (details.notes) {
    lines.push(`Notes,${sanitizeCSVValue(details.notes)}`);
  }
  
  lines.push('');
  lines.push('─'.repeat(80));
  lines.push('');

  // Footer with important information
  lines.push('IMPORTANT INFORMATION');
  lines.push('─'.repeat(80));
  lines.push('1. This report is for record-keeping and accounting purposes.');
  lines.push('2. The amounts are calculated after all deductions and fees.');
  lines.push('3. Payment settlement follows the agreed terms and conditions.');
  lines.push('4. For discrepancies or queries, contact support@convenehub.in');
  lines.push('');
  lines.push('This is an automated report generated by CONVENEHUB platform.');
  lines.push(`© ${new Date().getFullYear()} ConveneHub. All rights reserved.`);

  return lines.join('\n');
}

/**
 * POST /api/admin/settlements/email
 * Send settlement report email to movie team
 * 
 * Required: CONVENEHUB team role
 * Body: {
 *   event_id: string;
 *   movie_team_email: string;
 * }
 */
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();

    // Authenticate user
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    // Verify CONVENEHUB team role
    const { data: profile, error: profileError } = await supabase
      .from('profiles')
      .select('role, full_name')
      .eq('id', user.id)
      .single<Profile>();

    if (profileError || !profile || profile.role !== 'eon_team') {
      return NextResponse.json(
        { error: 'Forbidden - CONVENEHUB team access required' },
        { status: 403 }
      );
    }

    // Parse request body
    const body = await request.json();
    const { event_id, movie_team_email } = body;

    // Validate required fields
    if (!event_id || !movie_team_email) {
      return NextResponse.json(
        { error: 'Missing required fields: event_id, movie_team_email' },
        { status: 400 }
      );
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(movie_team_email)) {
      return NextResponse.json(
        { error: 'Invalid email format' },
        { status: 400 }
      );
    }

    // Fetch event details
    const { data: event, error: eventError } = await supabase
      .from('events')
      .select('event_id, title, date_time, status, ticket_price, convene_commission_percentage, settlement_status')
      .eq('event_id', event_id)
      .single<Event>();

    if (eventError || !event) {
      return NextResponse.json(
        { error: 'Event not found' },
        { status: 404 }
      );
    }

    // Check if event is eligible for settlement report
    if (event.ticket_price <= 0) {
      return NextResponse.json(
        { error: 'Cannot send settlement report for free events' },
        { status: 400 }
      );
    }

    // Fetch all confirmed bookings for this event
    const { data: bookings, error: bookingsError } = await supabase
      .from('bookings')
      .select('booking_id, tickets_count, total_amount, payment_status, booking_status')
      .eq('event_id', event_id)
      .eq('booking_status', 'confirmed')
      .returns<Booking[]>();

    if (bookingsError) {
      return NextResponse.json(
        { error: 'Failed to fetch booking information' },
        { status: 500 }
      );
    }

    // Calculate financial totals from confirmed bookings
    const totalTickets = bookings?.reduce((sum, b) => sum + b.tickets_count, 0) || 0;
    const grossRevenue = bookings?.reduce((sum, b) => sum + (b.total_amount || 0), 0) || 0;

    // Calculate fees using Decimal.js for precision - use event-specific commission
    const RAZORPAY_FEE_PERCENTAGE = 2;
    const eventCommissionPercentage = event.convene_commission_percentage || 10;
    const grossDecimal = new Decimal(grossRevenue);
    const razorpayFees = grossDecimal.mul(RAZORPAY_FEE_PERCENTAGE).div(100);
    const conveneCommission = grossDecimal.mul(eventCommissionPercentage).div(100);
    const netPayout = grossDecimal.minus(razorpayFees).minus(conveneCommission);

    // Try to fetch existing settlement data if it exists (explicit columns for email)
    const { data: settlement } = await supabase
      .from('settlements')
      .select(`
        settlement_id,
        event_id,
        gross_revenue,
        razorpay_fees,
        convene_commission,
        net_payout,
        transaction_reference,
        transfer_date,
        payment_method,
        notes,
        created_at
      `)
      .eq('event_id', event_id)
      .single<Settlement>();

    // Prepare settlement details for email
    const settlementDetails = {
      event_title: event.title,
      event_date: event.date_time,
      gross_revenue: settlement?.gross_revenue || parseFloat(grossDecimal.toFixed(2)),
      razorpay_fees: settlement?.razorpay_fees || parseFloat(razorpayFees.toFixed(2)),
      convene_commission: settlement?.convene_commission || parseFloat(conveneCommission.toFixed(2)),
      net_payout: settlement?.net_payout || parseFloat(netPayout.toFixed(2)),
      tickets_sold: totalTickets,
      settlement_status: event.settlement_status || 'pending',
      transaction_reference: settlement?.transaction_reference || undefined,
      transfer_date: settlement?.transfer_date || undefined,
      payment_method: settlement?.payment_method || undefined,
      notes: settlement?.notes || undefined,
    };

    // Generate CSV report
    const csvContent = generateSettlementCSV(settlementDetails, event, bookings || []);

    // Send email with CSV attachment
    const emailResult = await sendSettlementReport(movie_team_email, settlementDetails, csvContent);

    // Log the email send action in audit logs
    const auditLogData = {
      actor_id: user.id,
      actor_role: profile.role,
      action: 'SEND_SETTLEMENT_EMAIL',
      entity: 'settlements',
      entity_id: settlement?.settlement_id || event_id,
    };

    await supabase
      .from('audit_logs')
      .insert(auditLogData as any)
      .then(result => {
        if (result.error) {
        }
      });

    return NextResponse.json(
      {
        success: true,
        message: 'Settlement report sent successfully',
        email: movie_team_email,
        event_id: event_id,
      },
      { status: 200 }
    );
  } catch (error) {
    return NextResponse.json(
      {
        error: 'Failed to send settlement email',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
